version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.0.9-alpine #alpine 容器佔用空間較小，通常建議使用
    ports:
      - "6379:6379"
    restart: always

  nginx:
    container_name: nginx
    build: ./.nginx
    restart: always
    ports:
      # - "8080:80"
      - "80:80"
      - "443:443"
    volumes:
      - .:/mylinebot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./log:/var/log/nginx
    depends_on:
      - api

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email changchiarong@gmail.com --agree-tos --no-eff-email -d www.good-roader.tk
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./log:/var/log/letsencrypt

  api:
    container_name: api
    build:
      context: .
      dockerfile: .django/Dockerfile
    command: uwsgi --ini uwsgi.ini
    restart: always
    volumes:
      - .:/mylinebot
      # (HOST:CONTAINER)
    depends_on:
      - redis